apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: test-cilium
  namespace: monitoring-2
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: prometheus
