name: Run ClusterLoader2 Tests

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clusterloader2:
    name: Run ClusterLoader2 Scenarios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run ClusterLoader2 tests
        run: |
          go test -v -run ^TestRunClusterLoader2Scenarios$$ ./main_test.go
      - name: Collect scenario output artifacts
        run: |
          find scenarios -type d -name output | while read dir; do
            scenario=$(basename $(dirname "$dir"))
            mkdir -p "artifacts/$scenario"
            for f in "$dir"/*.json; do
              cp "$f" "artifacts/$scenario/$(basename $f)"
            done
          done
      - name: Upload scenario output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clusterloader2-artifacts
          path: artifacts/
