name: Run Kube-Burner Tests

on:
  workflow_call:
    inputs:
      NETPOL_CHURN_JOB_ITERATIONS:
        required: false
        type: string
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      NETPOL_CHURN_JOB_ITERATIONS:
        description: "Number of iterations for netpol churn job"
        required: true
        default: 5
        type: number

jobs:
  kube-burner:
    name: Run Kube-Burner Scenarios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run Kube-Burner tests
        env:
          NETPOL_CHURN_JOB_ITERATIONS: ${{ inputs.NETPOL_CHURN_JOB_ITERATIONS || github.event.inputs.NETPOL_CHURN_JOB_ITERATIONS || '1' }}
        run: |
          go test -v -run ^TestRunKubeBurnerScenarios$$ ./main_test.go
      - name: Collect scenario output artifacts
        run: |
          find scenarios -type d -name output | while read dir; do
            scenario=$(basename $(dirname "$dir"))
            mkdir -p "artifacts/$scenario"
            for f in "$dir"/*.json; do
              cp "$f" "artifacts/$scenario/$(basename $f)"
            done
          done
      - name: Upload scenario output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kube-burner-artifacts
          path: artifacts/
