global:
  indexerConfig:
    enabled: true
    metricsDirectory: ./my-custom-output

jobs:
  - name: kube-burner-job
    jobIterations: 5
    qps: 20
    burst: 40
    namespacedIterations: true
    cleanup: true
    namespace: kube-burner-job-ns
    jobPause: 1s
    objects:
      - objectTemplate: deployment.yaml
        replicas: 1
