name: Run ClusterLoader2 Scenario

on:
  workflow_dispatch:
    inputs:
      CL2_SCENARIO:
        description: "ClusterLoader2 scenario to run"
        required: false
        default: UniformQPS
        type: string

jobs:
  run-clusterloader2:
    name: Run clusterloader2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run clusterloader2 tests
        env:
          CL2_SCENARIO: ${{ github.event.inputs.CL2_SCENARIO || 'UniformQPS' }}
        run: |
          go test -v -run TestRunClusterLoader2Scenarios .

      - name: Collect executor output artifacts
        run: |
          find scenarios -type d -name output | while read dir; do
            executor=$(basename $(dirname "$dir"))
            mkdir -p "artifacts/$executor"
            zip -j "artifacts/$executor/output.zip" "$dir"/* || true
          done

      - name: Upload executor output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clusterloader2-artifacts
          path: artifacts/
