# This workflow is a convenience runner for local/CI testing.
# The canonical job definitions are in:
#   - .github/workflows/executors/kube-burner.yml
#   - .github/workflows/executors/clusterloader2.yml
#
# To update or add jobs, edit the files in .github/workflows/executors/ and reference them here as reusable workflows.

name: Run Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      NETPOL_CHURN_JOB_ITERATIONS:
        description: "Number of iterations for netpol churn job"
        required: true
        default: 5
        type: number

jobs:
  kube-burner:
    uses: ./.github/workflows/executors/kube-burner.yml
    with:
      NETPOL_CHURN_JOB_ITERATIONS: ${{ github.event.inputs.NETPOL_CHURN_JOB_ITERATIONS || '1' }}

  clusterloader2:
    uses: ./.github/workflows/executors/clusterloader2.yml
