name: Run Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      NETPOL_CHURN_JOB_ITERATIONS:
        description: "Number of iterations for netpol churn job"
        required: true
        default: 5
        type: number

jobs:
  run-executors:
    name: >-
     Run  ${{ matrix.executor }} Scenarios
    runs-on: ubuntu-latest
    strategy:
      matrix:
        executor: [kube-burner, clusterloader2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run ${{ matrix.executor }} tests
        env:
          NETPOL_CHURN_JOB_ITERATIONS: ${{ inputs.NETPOL_CHURN_JOB_ITERATIONS || github.event.inputs.NETPOL_CHURN_JOB_ITERATIONS || '1' }}
        run: |
          if [ "${{ matrix.executor }}" = "kube-burner" ]; then
            go test -v -run TestRunKubeBurnerScenarios .
          elif [ "${{ matrix.executor }}" = "clusterloader2" ]; then
            go test -v -run TestRunClusterLoader2Scenarios .
          fi

      - name: Collect executor output artifacts
        run: |
          find scenarios -type d -name output | while read dir; do
            executor=$(basename $(dirname "$dir"))
            mkdir -p "artifacts/$executor"
            zip -j "artifacts/$executor/output.zip" "$dir"/* || true
          done

      - name: Upload executor output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.executor }}-artifacts
          path: artifacts/
