name: Run Performance Tests

on:
  workflow_dispatch:
    inputs:
      NOTE:
        description: |
          This workflow is now split into two separate workflows:
          - kube-burner.yml
          - clusterloader2.yml
        required: false
        default: ''
        type: string

jobs:
  info:
    name: Info
    runs-on: ubuntu-latest
    steps:
      - name: Show info
        run: |
          echo "This workflow is now split into two separate workflows:"
          echo "- .github/workflows/kube-burner.yml"
          echo "- .github/workflows/clusterloader2.yml"
