name: Run Kube-Burner Scenario

on:
  workflow_dispatch:
    inputs:
      NETPOL_CHURN_JOB_ITERATIONS:
        description: "Number of iterations for netpol churn job"
        required: true
        default: 5
        type: number
      KB_SCENARIO:
        description: "Kube-Burner scenario to run"
        required: false
        default: netpolchurn
        type: choice
        options:
          - netpolchurn
          - apiintensive
      CLUSTER_SETUP_TYPE:
        description: "Cluster provider setup type"
        required: true
        default: kind-cilium
        type: choice
        options:
          - kind-cilium
          - azure-existing

jobs:
  run-kube-burner:
    name: >-
      Run kube-burner: ${{ github.event.inputs.KB_SCENARIO != '' && github.event.inputs.KB_SCENARIO || 'netpolchurn' }} on ${{ github.event.inputs.CLUSTER_SETUP_TYPE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run kube-burner tests
        env:
          NETPOL_CHURN_JOB_ITERATIONS: ${{ github.event.inputs.NETPOL_CHURN_JOB_ITERATIONS }}
          KB_SCENARIO: ${{ github.event.inputs.KB_SCENARIO != '' && github.event.inputs.KB_SCENARIO || 'netpolchurn' }}
          CLUSTER_SETUP_TYPE: ${{ github.event.inputs.CLUSTER_SETUP_TYPE }}
        run: |
          go test -v -run TestRunKubeBurnerScenarios .

      - name: Collect executor output artifacts
        run: |
          find scenarios -type d -name output | while read dir; do
            executor=$(basename $(dirname "$dir"))
            mkdir -p "artifacts/$executor"
            zip -j "artifacts/$executor/output.zip" "$dir"/* || true
          done

      - name: Upload executor output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kube-burner-artifacts
          path: artifacts/
